language: node_js
node_js:
  - "8"

script:
  - npm run ci

install:
  - npm install

cache:
  directories:
    - "node_modules"

deploy:
  provider: surge
  project: ./build/public
  domain: mapway.surge.sh
